exporter.csv.export = false
exporter.fhir.export = true
exporter.fhir.transaction_bundle = true
exporter.baseDirectory = ./output/jakarta_patients
exporter.years_of_history = 5
generate.vital_signs = true
generate.observations = true
generate.medications = true
generate.conditions = true
